baseURL = "http://localhost:1313/"
title = "Miguel Joaquin A. Sanson"
theme = "PaperMod"
languageCode = "en-us"

[params]
  defaultTheme = "auto"
  ShowShareButtons = false
  ShowReadingTime = false
  displayFullLangName = true
  hideFooter = true

  [params.profileMode]
    enabled = true
    title = "Miguel Joaquin A. Sanson"
    subtitle = "📍 Mandaluyong City, Philippines | Bachelor of Science in Information Technology<br>@ De La Salle University - Manila"
    imageUrl = "miguel.jpg"
    imageWidth = 200
    imageHeight = 200
    buttons = [
      { name = "View Profile", url = "#about" },
      { name = "Download Resume", url = "/Miguel-Joaquin-Sanson-Resume.docx" }
    ]

  [[params.socialIcons]]
    name = "email"
    url = "mailto:miguelsanson21@gmail.com"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/miguisanson"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com/in/miguel-joaquin-sanson-474703295"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "#about"
    weight = 10
  [[menu.main]]
    identifier = "experience"
    name = "Experience"
    url = "#experience"
    weight = 20
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "#projects"
    weight = 30
  [[menu.main]]
    identifier = "certifications"
    name = "Certifications"
    url = "#certifications"
    weight = 40

[markup.goldmark.renderer]
  unsafe = true
